### ISSUE TITLE
по дублям

### ISSUE THREAD

**Issue by ngie** [rpk-miet-ru/RP#254]
Ребят, ЛПМ волнуется, как в новой системе чистить дубли дисциплин. Хотят инструкцию какую-нибудь простенькую. или чтоб объяснили подошли, например.

**Comment by Sysa** [comment]
инструкции так и нет.... )

**Comment by MadridianFox** [comment]
Работать над такой серьёзной системой как ОРИОКС должен дипломированный специалист. Вот будет у специалиста диплом, тогда он и над инструкцией подумает xD
