### ISSUE TITLE
Открыть доступ к семестровым планам в интерфейсе студента

### ISSUE THREAD

**Issue by sokolovanat** [rpk-miet-ru/RP#287]
Семестровые планы должны быть открыты для студентов, а рабочая программ или сценарий обучения - нет

**Comment by MsNatali** [comment]
Семестровый план открыла. Но вот по поводу сценария обучения - у нас по САПУК ресурсы выложены как сценарий обучения. Вдруг не только тут и я таким образом закрою доступ к ресурсам, нужным для студентов
![screenshot01111](https://cloud.githubusercontent.com/assets/8089373/5815165/43805412-a0a4-11e4-8421-1cdfd7012cee.png)

**Comment by sokolovanat** [comment]
Сценарий обучения не должен быть доступен студентам. Значит неправильно дали тип ресурса. Как только преподаватели увидят , что ресурсы не видны студентам они их переименуют

Отправлено с iPad
