### ISSUE TITLE
по компетенциям

### ISSUE THREAD

**Issue by ngie** [rpk-miet-ru/RP#289]
Ребят, объясните мне, не понимающей по компетенциям ниче. Сейчас система работает или как?
я не могу найти после введения подкомпетенции ее нигде. как система функционирует в этом плане?) 
кафедрам надо разложить на подкомпетенции компетенции и прикрепить их к дисциплинам?) у меня вот не получилось.

**Comment by MadridianFox** [comment]
Со стороны кафедры система не работает.
Т.е. подкомпетенции не создаются.
Пытаюсь исправить, как сделаю всех уведомлю =)

**Comment by ngie** [comment]
ну как там компетенции собственно?)

**Comment by MadridianFox** [comment]
Я близок к разгадке тайны семантически связанного острова...
На самом деле осталось совсем чуть чуть и оно сегодня-завтра будет готово.

**Comment by ngie** [comment]
оки оки) ждем=)

**Comment by MadridianFox** [comment]
Так. ПКВ компетенции создаются. На подкомпетенции всё декомпозируется.

**Comment by ngie** [comment]
ок) круто)
а какая-то инструкция по работе с компетенциями планируется? =)

**Comment by MadridianFox** [comment]
Мне бы инструкцию по работе с устранение дублей сделать... ^_^
Но ладно, пора перестать играть в танки и начать равняться на лауреатов всероссийского чего-то там.., пойду чё-нибудь придумаю)

**Comment by ngie** [comment]
вот вот)
а лауреат просит прямо уже слезно...

**Comment by MadridianFox** [comment]
Для компетенций инструкция готова

**Comment by ngie** [comment]
круто, спасибо) там Короткевич проверила. Вопрос: если удалить вид деятельности, его компетенции остаются в списке, это хорошо или все же не очень?

**Comment by MadridianFox** [comment]
Это она где такое нашла?
Попробовал удалить вид деятельности у НП - компетенции этого вида пропали
Попробовал удалить вид деятельности у БУПа - компетенции этого вида пропали

**Comment by ngie** [comment]
вот тут: отображаются в списке УП компетенции к орг-упр деятельности

![image](https://cloud.githubusercontent.com/assets/9082000/5954759/d64af4b4-a7ac-11e4-9a10-555816732524.png)
