### ISSUE TITLE
компонент "управление содержанием" и его связь с ИС

### ISSUE THREAD

**Issue by Sysa** [rpk-miet-ru/RP#291]
Товарищи, будьте так любезны, подскажите мне что вам ещё нужно для включения компонента на все остальные страницы системы.
Сейчас на входе банально ловится параметр - id дисциплины (dis_id)
К примеру: http://orioks.miet.ru/sandbox/khlopov/?dis_id=19069
При некорректном ID - вылезет ошибка.
Плюс ко всему берётся RPRole::userID(); и подставляется везде, где нужно. Поэтому пример выше работает только под логином преподавателя дисциплины (т.е. Соколова Н.Ю.).
Если связь отсутствует у преподавателя и дисциплины, вылазит лишь кусок информации без особых действий, можно это решить вопросом запроса к БД (а может есть готовая проверка на связь дисциплины + преподавателя в API? - не нашёл). Но по идее от туда, где будет ссылка на интерфейс, "левый" пользователь и не попадёт. Ладно, это не так критично и решаемо.
Лучше расскажите мне что и где вы будете цеплять и что вам для этого надо.
p.s. back-end пока что висит в песочнице, тут тоже вопрос: как подрубить подключение к БД, не подрубая футер и хедер со всем мусором (в back-end'e) ?

**Comment by MadridianFox** [comment]
Начну с конца. В компонентах есть прекрасный механизм для аякса. Кладёшь файлы аякс обработчиков в специальную папку (без футеров и прочего), и они доступны тебе по ссылке вида:
/ajax/?action=<component>/<filename>

**Comment by MsNatali** [comment]
Не вдаваясь в подробности что ты сделал, сразу скажу:

Есть прекрасный механизм ограничения прав доступа к компоненту в зависимости от текущей роли.
Делать это обязательно.
Настраивается он в общем тут http://orioks.miet.ru/sandbox/ob/permission.php
и потом в каждом файле в начале пишешь примерно такое
if(!RPRole::getPermitOne('upd')) RPH::errorPage("Ошибка доступа");

**Comment by MsNatali** [comment]
И ещё если роль - методист, то он может работать целиком с данными, хоть и дисциплину не ведет.

**Comment by MsNatali** [comment]
По поводу твоего вывода ошибки - делай так RPH::errorPage("Текст ошибки");
Тут сразу подключается почта и выглядит более заметно
![screenshot01120](https://cloud.githubusercontent.com/assets/8089373/5946953/982fed18-a74a-11e4-88ec-017bdbddd36f.png)

**Comment by MsNatali** [comment]
а почему там написано "пулл"? должно быть "пул"

**Comment by Sysa** [comment]
Дрянное слово "пулл" заменено на прекрасное и восхитительное "пул".
Прекрасный механизм вывода ошибки RPH::errorPage добавил.
Прекрасный механизм для аякса - использовано, работает.
Не вдаваясь в подробности прекрасного механизма ограничения прав доступа к компоненту в зависимости от текущей роли, сразу спрошу:
Мне нужно свой объект создать или можно использовать прекрасные объекты с преподавателем и методистом, например:
dolg_schedule;
fgos_of_journal;
journal_edit;
Или они могут в дальнейшем изменяться и стоит всё-таки создать свою избу с преподавателем и методистами?
Необходимо ли ещё что-нибудь настраивать в прекрасном механизме ограничения прав доступа к компоненту в зависимости от текущей роли?

**Comment by MsNatali** [comment]
Обязательно свой.

Ну и в файлы добавить проверку, имеет ли текущий пользователь доступ к компоненту с помощью функции RPRole::getPermitOne('journal_edit')

**Comment by Sysa** [comment]
Прекрасный механизм ограничения прав доступа к компоненту в зависимости от текущей роли работает, добавленный объект носит не менее прекрасное название "dis_content_management".
Как говорится, what's next?

**Comment by Sysa** [comment]
Скрипт записи сделал и он отработал. за 17 минут работы скрипта добавилось 126334 записей в таблицу ir_dis_gr.
что осталось сделать:
-вывести ссылку на интерфейс;
-добавить фильтр в интерфейсе студента;
-возможно какие-то небольшие поправки и изменения во внешнем виде интерфейса;

**Comment by Sysa** [comment]
Сам компонент носит название "content_management"
на входе ловит ID дисциплины - "dis_id", например (?dis_id=19069)
доступ к компоненту только у преподавателей, прикрепленных к переданной дисциплине и методистов соответственно.
таблица, с которой оперирует компонент носит название "ir_dis_gr", столбцы (3 шт.) имеют названия:
-id_ir - идентификатор ИР;
-id_tup_d - идентификатор объекта "ТУП+Д";
-gr - идентификатор студенческой группы;
все типа bigint и первичные ключи.

**Comment by Sysa** [comment]
Вопрос: ссылка всё-таки будет из пула или из текущих дисциплин ? у меня в блокноте написано сначала "переход на компонент из текущих дисциплин", а потом "ссылка на компонент из пула".

**Comment by Sysa** [comment]
ещё забыл:
надо сделать фильтр по семестру как в текущих дисциплинах, это я тогда попозже сделаю.
Что от меня ещё требуется для успешного подключения компонента в ИС?

**Comment by Sysa** [comment]
поправил скрипт по заполнению, теперь прикреплены только типы ИР с номерами 8,10,12,15,16,17,18,19,20,29,30,47,70,71 и в случае 12-го отсеиваются линки с содержанием "/oroks-miet/".
Проверил, вроде отработало нормально, если есть возможность точно проверить ещё где-нибудь - посмотрите пожалуйста.

**Comment by Sysa** [comment]
Добавил проверку на методиста:
методисту отображаются все группы,
преподавателю - только его.
проверил на дисциплине 19033, работает.

**Comment by Sysa** [comment]
добавил фильтр по семестру, протестировал, работает.
компонент принимает теперь rp_dis_id на входе get-параметром
