### ISSUE TITLE
Загрузка файлов на сервер ИС

### ISSUE THREAD

**Issue by Sysa** [rpk-miet-ru/RP#292]
Файлы у нас можно грузить в основном в двух местах, как я понял (взгляд со стороны студента):
1. Личные файлы - видны только нам.
2. Портфолио - видны по указанным параметрам. (дисциплина и т.п.)
Чтобы не ковырять лишний раз код, задаю вопросы:
Через что происходит взаимодействие и какими программными средствами ( API, например ) можно сейчас воспользоваться чтобы залить файл\ссылку на сервер (портфолио и своё личное пространство)?
Какие есть механизмы и как с ними можно поиграться в песочнице?
Куда в итоге происходит заливание файлов\ссылок?
Заранее благодарю, товарищи!

**Comment by Sysa** [comment]
Any ideas?!
Или можно смело начинать майнинг кода и городить костыли?

**Comment by MadridianFox** [comment]
А тебе зачем?)

**Comment by Sysa** [comment]
Так и знал что этот вопрос будет первым.
Интерес чисто диссертационный и направление от ИГИ изучить этот вопрос.

**Comment by MadridianFox** [comment]
Механизм:
Файл загружается на сервер 152 сервер (ориокс) как обычно.
через ftp копируется на 148 сервер (ороск)
в mysql на 148 сервере в eav подобную БД записывается информация о файле, если загружается ссылка, то просто создаётся запись в БД, без файла =)
API:
есть класс RPOrioks в котором собраны функции для загрузки/удаления файлов и работы с информацией о них. Лишний раз с этим лучше не ковырятся, (_._) чую, там скоро что-то лопнет.
Используется:
- в портфолио
- в личных файлах
- при загрузке ИР
