### ISSUE TITLE
еще по правам доступа:БИБЛИОТЕКА

### ISSUE THREAD

**Issue by ngie** [rpk-miet-ru/RP#293]
мне кажется мы обделили библиотеку в ориоксе...
у них был доступ в дисциплину и там у них раздел по заполнению списка литературы был, кажется как то так.

**Comment by MsNatali** [comment]
во все дисциплины всех кафедр?
И там они заполняли только ИР типа "Список литературы"?
А к остальным ресурсам доступ имели?

**Comment by ngie** [comment]
да нет вроде б. остальные ресурсы их не интересовали

**Comment by MsNatali** [comment]
Вот эти "кажется как-то так" и "вроде б" настораживают. можно как-то поточнее узнать? =)

**Comment by ngie** [comment]
ну я уточнила. к КАЖДОЙ дисциплине ТОЛЬКО список литературы.
нужен доступ Филлиповой и Хусаиновой. или там все отделом по t дается доступ?)

**Comment by MsNatali** [comment]
Я сейчас мучаю список КМ для должников. Закончу - сделаю это

**Comment by ngie** [comment]
пасиба=)

**Comment by ngie** [comment]
как насчет библиотеки?)

**Comment by MsNatali** [comment]
Готово. Пускай проверят.

**Comment by ngie** [comment]
ок, спасибо, передам им.

**Comment by ngie** [comment]
А у библ проблемы: 
У Хусаиновой вот так:
![image](https://cloud.githubusercontent.com/assets/9082000/6038827/c0ad0ba0-ac71-11e4-9770-5085f810bf12.png)
У Филипповой еще и права какие то странные...
![image](https://cloud.githubusercontent.com/assets/9082000/6038876/27e33060-ac72-11e4-8744-0070654657de.png)
но в целом у них ничего не работает. я под библиотекой зашла- у меня то все ок)

**Comment by MsNatali** [comment]
права я не трогала. значит в группах, котоым были назначены эти права она состояла до перехода в нашу систему.
ограничение доступа убрала

**Comment by ngie** [comment]
ну у них че то не грузится. вернее в списке материалов не отображается, хотя они загрузили.
дисциплина бмс
![image](https://cloud.githubusercontent.com/assets/9082000/6056729/17d76b8c-ad26-11e4-9f87-2f902ef64286.png)
и
![image](https://cloud.githubusercontent.com/assets/9082000/6056731/2735c4ca-ad26-11e4-8458-87f5f6f671b1.png)
тут они попробовали.
как то так)

**Comment by ngie** [comment]
вроде загружают то они правильно, мы сней процедуру прошли.

**Comment by MsNatali** [comment]
Загрузили это хорошо. А прикрепили?)

**Comment by ngie** [comment]
так. 1) они не в праве изменить тип документа: учебные ресурсы, а где им указывать, что это ссылка на литературу?
2) как происходит процедура прикрепления? они ж вроде открывают дисциплину и загрузку делают уже к дисциплине,не?

**Comment by MsNatali** [comment]
ну ёёёё. Ну все вообще не так.
Это не тип ИР. это тип документов. И форма слева для загрузки файлов на сервер, а не для работы с содержимым. 

И вообще. сама же требуешь инструкции и не читаешь их никогда, да?)

**Comment by ngie** [comment]
мне и интсрукции  ваши не айс.
но. мы разобрались с библ. тока вот там выдается такой одинаковый список-по дате тяжело нужный файл найти
![image](https://cloud.githubusercontent.com/assets/9082000/6058551/7a54832c-ad39-11e4-8087-2e629fba3393.png)
поэтому, нельзя ли, не будете ли вы так любезны, сделать им отображение названия самого файла, как они его грузили?) или это нереальные наши фантазии?

**Comment by MsNatali** [comment]
Ох сколько иронии-то

**Comment by MsNatali** [comment]
Держите

**Comment by ngie** [comment]
спасибо=*

**Comment by ngie** [comment]
куку. а еще им надо фильтр по семестру в фильтре кафедры=)
очень надо.

**Comment by MsNatali** [comment]
в каком фильтре кафедры? ты о чем? Это ПУЛ дисциплин, тут нет семестров

**Comment by ngie** [comment]
но в пуле они не могут работать значит.
им нужны именно текущие.
список лит-ры подготавливается на семестр.
как им посмотреть текущего семестра дисциплины?

**Comment by MsNatali** [comment]
Через что бы ты ни смотрела на дисциплину, добавляя что-то в нее оно будет доступно и тем кто изучал дисциплину ранее, и тем кто сейчас. Это же содержимое не в рамках ТУП+Д. Так что какая разница через что? они же знают название дисциплины и по названию есть фильтр...
