### ISSUE TITLE
нужно обновить списки преподавателей кафедры

### ISSUE THREAD

**Issue by Irina1209** [rpk-miet-ru/RP#294]
В списках ЭиМ числятся 

1.      Алаева Ольга Геннадьевна – каф. МиУП

2.      Дабахьян Наталья Алексеевна – каф. МиУП

3.      Костина Галина Дмитриевна – каф. МиУП

4.      Филиппова Татьяна Петровна - ?

5.      Шутова Елена Андреевна - ?

**Comment by Irina1209** [comment]
У ПКИМС в списке преподавателей появился Усов, преподаватель кафедры ВМ-2.

**Comment by Irina1209** [comment]
Усов мог появиться из-за того, что мы правили дисциплину  "Методы математического моделирования". Я писала 04.02 что, у группы ПКИМС-12 отсутствует дисциплина .
Эта дисциплина сейчас в списке дисциплин кафедры ВМ-2 (раньше ВМ-2 читали эту дисциплину), а сейчас ее читает ПКИМС

**Comment by MadridianFox** [comment]
Ни Дмитрий, ни Пвел Усовы в базе данных ОРИОКС к кафедре ПКИМС не прикреплены.

**Comment by Irina1209** [comment]
он выплыл в списке кафедры ПКИМС в отчете "Преподаватели дисциплин" (см.последняя строка)

**Comment by MsNatali** [comment]
Ну тут все понятно...

Усов, был прикреплен к ТУП+Д (связь дисциплины с учебным планом), когда дисциплина принадлежала ВМ-2. 
От того что дисциплину перенесли на ПКИМС, связь преподавателя с ТУП+Д никуда не делась.

Отчет показывать всех преподавателей, прикрепленных к ТУП+Д, вот он и появился.


Сейчас интерфейс назначения преподавателей не показывает прикрепленных преподавателей, не относящихся к этой кафедре, но завтра я сделаю так, чтобы показывал и тогда сообщите преподавателям, чтобы открепляли таких преподавателей.

**Comment by MsNatali** [comment]
Откреплять преподавателей не своей кафедры теперь можно
