### ISSUE TITLE
компонент user_files и загрузка ссылок

### ISSUE THREAD

**Issue by Sysa** [rpk-miet-ru/RP#295]
1. если загружать ссылку, которая ведёт на защищенный HTTP, то обрезает двоеточие и ссылка становится не рабочей, пример:
http://miet.ru - работает, ссылка загружена нормально
https://miet.ru - не работает, ссылка сохраняется без ":" двоеточия.
Там либо ссылка сохраняется без http/https и подобных, аля "miet.ru", а потом в коде подставляется уже при выводе ссылки из БД, либо что-то другое. В любом случае не зер гуд и надо исправлять.

2. длина ссылки 254 символа, если в ссылке присутствуют кириллические символы, которые, как мы прекрасно знаем, переделываются в байты юникода, записанных в шестнадцатиричном представлении и разделённых символом %. Таким образом, 4 символа "миэт" будут занимать аж "%D0%BC%D0%B8%D1%8D%D1%82" - очень много.
и ссылка на файл под названием "Функциональные требования магистратура миэт 2015" займёт уже 248 символов в таком представлении. А ещё нужен адрес сервера, спец.символы и тупо путь до файла, который как правило похлеще названия может быть.
По всей видимости ограничение не в инпуте и его maxlength, а в типе поля БД. Совсем не зер гуд.

В итоге 3 из 5 моих ссылок - не работали =) одна была https, две - тупо не влезли, оставшиеся две были на miet.ru

Вопрос: кто, как, когда? нужна ли помощь?

P.S. Если "для чего?!" - то ответ всё такой же - "для диссертации".

**Comment by Sysa** [comment]
Предполагаю, в компоненте по загрузке в портфолио (не пользовательские файлы) аналогичные проблемы.

**Comment by MadridianFox** [comment]
https регуляркой не взялся. Поправим как-нибудь.
254 символа это ограничение БД. БД не наша, так что вот. Вообще не знаю зачем нужна возможность сохранять ссылки..

**Comment by Sysa** [comment]
https - понял.
возможность сохранять ссылки нужна для того, чтобы не забивать наш сервак я полагаю. Или если большой файл (видео какое-нибудь или ещё что) - не грузить его повторно, если он загружен уже где-нибудь или банально ссылки на сторонние ресурсы.
Чья БД и кому писать ?

**Comment by MadridianFox** [comment]
эмм.. незнаю =)

**Comment by bereza-evgenij** [comment]
С длинной ссылки увеличил до 5000 символов

**Comment by Sysa** [comment]
спасибо! :) но что странно - всё равно обрезает в 255 символов, при этом добавляя http://
т.е. тупо взять строку из одной и той же буквы, например "а" (длина этой строки 3600 символов, например) и записать как ссылку - в итоге в сохранённых файлах (ссылке) следующая схема:
http://ааааа....аааа
получается что на выходе обрубать даже может. буду копать дальше!

**Comment by bereza-evgenij** [comment]
Эта проблема еще актуальна?

**Comment by Sysa** [comment]
пока думаю да, попозже будет виднее )
