### ISSUE TITLE
А чем отличаются права с шифром dis (Просмотр ПУЛа дисциплин) и pul (Просмотр ПУЛа дисциплин)?

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#299]

**Comment by MsNatali** [comment]
ничем )

**Comment by bereza-evgenij** [comment]
Тогда может одну delete, а то в модуле обратно связи в списке дубль, если у
роли два таких права

**Comment by MsNatali** [comment]
удали dis, только проверь чтобы и для лпм в стправочнике объектов ссылка осталась, и доступ в общем нигдеи не потерялся

**Comment by bereza-evgenij** [comment]
Удалил пока права доступа всех ролей к dis. У кафедр пропала вкладка пул, но это просто была ошибка в файле с меню раздела Подготовка  - там проверялось право dis. Внутри компонента проверяется наличие права pul. То же самое было в верхнем меню всего портала.
Право dis я пока не удалял

**Comment by MsNatali** [comment]
Удаляю эту функцию и закрываю тикет
