### ISSUE TITLE
ошибка при проставлении баллов в мп-17 ОФ

### ISSUE THREAD

**Issue by ngie** [rpk-miet-ru/RP#300]
дисциплина 
![image](https://cloud.githubusercontent.com/assets/9082000/6598626/029b99d6-c816-11e4-88f8-5efdf97828a4.png)
воспользовались 
![image](https://cloud.githubusercontent.com/assets/9082000/6598634/1b29ac36-c816-11e4-99ae-24263b07993d.png)
и выдает ошибку:
![image](https://cloud.githubusercontent.com/assets/9082000/6598609/d99a6206-c815-11e4-84fb-24b76d1eb63c.png)

**Comment by MsNatali** [comment]
Отлично, а ошибочные баллы за экзамен вас не волнуют?

Кстати от куда это они там взялись?

**Comment by ngie** [comment]
а как они их умудрились туда ввести?

**Comment by MsNatali** [comment]
ну как вариант - сначала были поставленны баллы, а потом изменено КМ.
Но вообще странная ситуация

**Comment by ngie** [comment]
там лпм че то с планами мудил. менял, окреплял и тд

**Comment by ngie** [comment]
шеф, че теперь делать?)

**Comment by MsNatali** [comment]
а в чем проблема?

Удаляем все баллы за экзамен и забываем об этом. Удалить преподаватель и сам может (просто стереть балл из ячейки и сохранить это)

**Comment by ngie** [comment]
у меня эта ячейка для редактирования не доступна че то

**Comment by MsNatali** [comment]
что? это как?

**Comment by ngie** [comment]
да доступно все ок. не заметила прокрутки=)
