### ISSUE TITLE
ссылка на компонент "управление содержанием" и его размещение.

### ISSUE THREAD

**Issue by Sysa** [rpk-miet-ru/RP#302]
Компонент content_management доделан, на него должны выходить преподаватели и методисты из дисциплин (не помню, пула или текущих?, по-моему пула всё-таки, если не так - поправьте).
По моей логике надо:
1. Разместить где-то компонент, а не в песочнице. Т.е. вывести где-либо. - Кто займётся? Дзен размещения компонентов мне не дан с рождения, поэтому смотрите сами относительно правильности структуры всей системы ОРИОКС.
2. Сделать на размещенный компонент ссылку. - Кто займётся? Не являюсь специалистом по стилям бутстрапа и его каноничных ссылок в системе ОРИОКС, так что тут тоже сами, пожалуйста.

p.s. ещё, возможно, требуются изменения в интерфейсе студента, но это уже другая проблема - https://github.com/rpk-miet-ru/RP/issues/301

Если что требуется от меня - напишите.
Компонент называется "content_management", на входе принимает GET-параметр "rp_dis_id", в котором передаётся ID дисциплины. Работает для ролей "преподаватель" и "методист".

**Comment by MadridianFox** [comment]
А html в шаблон кто перемещать будет?
и JS в отдельный файл
ато у тебя каша в компоненте и пустой template

**Comment by Sysa** [comment]
это влияет на производительность или конечный результат и возможности компонента ?

**Comment by MadridianFox** [comment]
Это влияет на производительность программиста, которому однажды придётся вносить правки в компонент

**Comment by Sysa** [comment]
это никак не относится к внедрению модуля или размещению компонента

**Comment by MadridianFox** [comment]
конечно не относится
но если сейчас не сделать то оно так и останется

**Comment by Sysa** [comment]
Если этот компонент сейчас не подключить - вот оно реально так и останется висеть без дела, до следующего студента с его выпускной работой/курсовой.
По существу ещё есть проблемы с данным компонентом?

**Comment by MadridianFox** [comment]
думаю нет

**Comment by MadridianFox** [comment]
компонент разместил, ссылку сделал
![work_image](https://cloud.githubusercontent.com/assets/3392587/6664836/39035f6e-cbe4-11e4-9f5c-db8cb9d6a71d.png)

**Comment by Sysa** [comment]
Всё отлично работает, спасибо!

**Comment by Sysa** [comment]
Надо добавить ещё семестр в ссылку, при переходе.
компонент ловит "sem=XXXX-Y", где XXXX-год, а Y - локальный семестр.
Иначе приходится всегда заново фильтровать группы относительно текущего семестра.

**Comment by MsNatali** [comment]
Ну семестр в месте, от куда переходят, есть не всегда

**Comment by bereza-evgenij** [comment]
Ну когда есть тогда и передовать

**Comment by MsNatali** [comment]
Я понимаю. Вопрос в том сломает ли отсутствие в ссылке семестра его компонент, или у него заглушка стоит

**Comment by bereza-evgenij** [comment]
Там вроде есть заглушка. Но последнее слова за Сашей

**Comment by Sysa** [comment]
Заглушка есть. Если нет семестра, то вставляется текущий через RPU::getNowSem();
При переходе на компонент с "&sem=", т.е. пустым или без него вовсе - результат один: выводит группы текущего семестра. так что смею предположить, что заглушка рабочая.
