### ISSUE TITLE
Изменения по отчёту "Заполнение журналов"

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#305]
По просьбе ОКиО необходимо:
1. Добавить фильтр по столбцу Примечание.
2. Добавить возможность формирования отчета по всем кафедрам (если это можно)
3. В списке кафедр поправить сортировку по алфавиту (кафедра ИБ в самом низу сейчас)

**Comment by MsNatali** [comment]
загрузка по всем кафедрам сразу нет

**Comment by bereza-evgenij** [comment]
Ок

**Comment by bereza-evgenij** [comment]
Фильтр по столбцу Примечание не работает
