### ISSUE TITLE
Сортировка КМ по неделям

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#308]
В инструменте импорта баллов КМ в верхнем графике сортировать КМ по неделям. Так сопоставлять КМ будет проще, т.к. КМ сами чаще всего будут выстраиваться друг по другом

![default](https://cloud.githubusercontent.com/assets/7606944/6891518/e8b6b314-d6cc-11e4-988f-f745ff40f544.PNG)

**Comment by bereza-evgenij** [comment]
Там еще опечатка в сообщении 
![image](https://cloud.githubusercontent.com/assets/7606944/6891548/524139d0-d6cd-11e4-8197-a64fcd325fa7.png)

**Comment by bereza-evgenij** [comment]
И думаю для проверки правильности сопоставления КМ было бы очень удобно, если бы у сопоставленных КМ, в случае коэффициента=1, проверялось равенство типов КМ и диапазонов [min;max]. Если что-либо из них не совпадает, то подсвечивать такие КМ красным цветом.
Проверять равенство недель и названий КМ думаю не нужно, т.к. недели могут отличаться из-за разницы в расписании занятий, а названия КМ могут содержать лишние пробелы, либо орфографические ошибки, хотя по смыслу быть одинаковыми

**Comment by bereza-evgenij** [comment]
А еще я заметил, что можно одному КМ сопоставить несколько КМ. Ты это специально учитывала при разработке, и каким образом тогда будет происходить импорт баллов? 
Мне кажется отношения 1 ко многим быть не должно и программа это тоже должна отслеживать

**Comment by bereza-evgenij** [comment]
А столбец Группы в самой верхней таблице разве должен быть пустым?

**Comment by bereza-evgenij** [comment]
Если нажать на Показать баллы, то таблица не вмещается во всплывающее окно
![image](https://cloud.githubusercontent.com/assets/7606944/6892016/f95dab4c-d6d0-11e4-8a48-4adce45124cf.png)

**Comment by bereza-evgenij** [comment]
Каким образом нужно определить коэффициент, чтобы не было такой ошибки?
![image](https://cloud.githubusercontent.com/assets/7606944/6892080/b93deda0-d6d1-11e4-9d2f-ad021bf52623.png)
Ругается он видимо на это
![image](https://cloud.githubusercontent.com/assets/7606944/6892088/cead296c-d6d1-11e4-9cf2-a38350ae1dd3.png)
Но у студентов нет баллов, которые бы не попали в отрезок от [0;3]
![image](https://cloud.githubusercontent.com/assets/7606944/6892107/f9438892-d6d1-11e4-8216-6d4e9b736310.png)

**Comment by MsNatali** [comment]
1. Проверять типы думаю не надо. Т.к. и они могут отличаться (например Активность и Активность/Посещаемость)
2. Пустой столбец "Группы" говорит о том, что в старом учебном плане группы теперь нет ни одной группы.
3. Да, я специально делала так, что из одного КМ можно импортировать в несколько. И зачем убирать эту возможность?
4. С вылезающей за края таблицей сделать ничего не могу. И так использую самую большую модалку из возможных. На такой случай там есть возможность экспорта в эксель
5. Подразумевается, что минимальный и максимальный баллы в итоге должны быть равны. Можно сделать так, чтобы отрезок min:max ИЗ которого импортируется был хотябы Ванутри отрезка min:max КУДАи импортируется, а не обязательно равно.

**Comment by bereza-evgenij** [comment]
1. Активность и Активность/Посещаемость это немного разные типы КМ. Типы КМ точно нужны, т.к. диапазон баллов может совпадать у многих типов КМ.
2. Тогда может его совсем убрать? Какая от него польза?
3. Просто непонятно, каким образом будут разделены баллы этого КМ на несколько КМ. Преподавателю мало того, что нужно будет указать в коэффициенте какую часть баллов КМ нужно взять, да к еще и попасть в диапазон [min;max] конечного КМ, при этом нужно умудриться из N исходных баллов получить баллы для Mконтрольных мероприятий, чтобы их сумма была равна N. Преподавателю для всего это нужно будет решить систему уравнений из M+1 уравнений, причем M из них будут неравенствами.
4. А нельзя сделать горизонтальную прокрутку, так же как и для графиков КМ из этого интерфейса?
5. Да, я думаю, что лучше сделать именно такую проверку. Но все равно, если сопоставленные КМ имеют разные отрезки [min,max], то их выделять красным (просто для информации).

**Comment by MsNatali** [comment]
2. Это в случае когда группу целиком перевели никакой. а когда речь идет о переходе студентов из других групп в текущую - нужно
3. А чего так сложно то. Тут речь идет о случаях, когда был один например, тест, а стало 2. Тем более этот запрет легко будет обходится обновлением страницы и копированием в другое КМ.
4. Об этом чет не подумала. Будет

**Comment by bereza-evgenij** [comment]
А как сопоставлены твои 3 пункта с моими 5? :)

**Comment by MsNatali** [comment]
гитхаб решил плевать на мою нумерацию, и ставить свою. должно быть так
![screenshot01176](https://cloud.githubusercontent.com/assets/8089373/6896287/6dc69338-d6f2-11e4-982c-c024ca406d40.png)

**Comment by bereza-evgenij** [comment]
2. С этим понял, оставляем как есть.
3. Ладно, с этим вариантом я согласен, в случае когда тест по одной теме разбивают на два мелких теста. Но случай конечно редкий и у нас вряд ли кто будет этим пользоваться. В целом хорошо, что такая возможность есть. Но вот способ расчета мне все равно в этом случае не понятен. Многим преподавателям думаю тоже. А что за способ с обновлением страницы и копированием в другое КМ, не понял этого?

**Comment by MsNatali** [comment]
Да ничем способ расчета не отличается от 1 к 1. При желании можно просто дублировать баллы из 1 КМ в 2 КМ.

**Comment by bereza-evgenij** [comment]
Ну вот то, что в этом случае у студента могут появиться новые баллы очень странно с точки зрения здравого смысла :)

**Comment by bereza-evgenij** [comment]
Наташ, а ты не делала "И думаю для проверки правильности сопоставления КМ было бы очень удобно, если бы у сопоставленных КМ, в случае коэффициента=1, проверялось равенство типов КМ и диапазонов [min;max]. Если что-либо из них не совпадает, то подсвечивать такие КМ красным цветом."? 
Было бы очень удобно для проверки
