### ISSUE TITLE
Изменения в журнале должников

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#309]
1. Пока решили убрать столбец с оценкой, а вместо него добавить столбец "Сумма баллов в семестре", в котором нужно вывести сумму всех закрытых в течение семестра КМ.
2. Добавить вывод успеваемости студентов по КМ в течение семестра. При нажатии на ФИО студента в журнале должников скрывать всех остальных студентов, а внизу отображать отрезок из основного журнала по дисциплине для этого студента (т.е. оставить только шапку таблицы с перечнем КМ и строку с баллами студента). Либо эту информацию можно отображать во всплывающем окне. Делайте так, как будет проще реализовать

**Comment by MsNatali** [comment]
2. А чем плох вариант сделать ссылку на основной журнал?

**Comment by bereza-evgenij** [comment]
Тем что преподавателю нужно в другом окне искать нужных ему студентов, причем в журнале по должникам могут быть студенты из разных групп и поэтому таких журналов нужно будет открывать несколько, да еще в каждом из них искать нужного студента.
Ну и ты читала реакцию Тимошенко насчет ссылки на журнал. Думаю похожая реакция будет и у других преподавателей.

**Comment by MsNatali** [comment]
А тыкать на каждого студента отдельно намного лучше?

**Comment by bereza-evgenij** [comment]
Тоже не очень, но хотя бы в одном окне это все происходит. Может тогда под каждой строкой со студентом сделать строку со всеми объединенными столбцами и в эту длинную ячейку вставлять вырезку успеваемости студента из журнала? Но будет конечно громоздко смотреться, и тебе я думаю на angular это будет не так просто реализовать

**Comment by MsNatali** [comment]
Ну ты придумал тоже. Это ж жуть как будет выглядеть. может лучше сделать сделать ссылку на небольшой компонент, в котором будут в виде журнала показываться оценки всех должников по старому семестру? Да будет на другой странице, по будет лучше так, чем по каждому студенту кликать, м?

**Comment by bereza-evgenij** [comment]
Щас я Тимошенко напишу, пусть свой вариант предложит
