### ISSUE TITLE
Изменения по интерфейсу работы с дисциплинами БУПа/ТУПа

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#310]
ЛПМу для проверки учебных планов к аккредитации нужны следующие доп. возможности:
1. Добавить возможность обновления/добавления дисциплин в ТУПе на основании БУПа в выбранном семестре. Т.е., например, ЛПМ редактирует дисциплины БУПа для 5 семестра, а потом в БУПе нажимает на кнопку "Обновить дисциплины ТУПа", и в ТУПе если в 5 семестре не было дисциплин, то они добавляются из БУПа, если дисциплины уже были, то должна быть проверка на наличие графиков КМ и прочих объектов, связанных с объектом ТУП+Д, и если таких объектов нет, то дисциплины также обновляются. В противном случае не обновлять дисциплины ТУПа и вывести сообщение об этом (желательно со списком дисциплин, в которых что-то есть).
2. Для дисциплин БУПов и ТУПов добавить массовое удаление всех дисциплин. У значения семестра "Не важен" тоже добавить кнопку на удаление, как это сделано по отдельным семестрам.
3. К таблице дисциплинам БУПов и ТУПов добавить вывод кафедры (после семестра) и названий всех ООП дисциплины (перед столбцом с действиями). И столбец с действиями продублировать перед названием дисциплины.

**Comment by MsNatali** [comment]
1. Я бы сделала только добавление. А редактирование не нужно, т.к. если данные не были переопределены в самом ТУП, то они и так берутся из БУП, а если их переопределили, то не вижу смысла их стирать.
2. ОК
3. ОК

**Comment by bereza-evgenij** [comment]
1. Давай пока сделаем только добавление дисциплин семестра в том случае, если дисциплин в ТУПе для этого семестра нет. Остальное нужно обсуждать с ЛПМ и ИГИ

**Comment by MsNatali** [comment]
1 сделаю позже
2 и 3 готово, посмотри

**Comment by bereza-evgenij** [comment]
Хотел проверить массовое удаление дисциплин, создал тестовый БУП 2023 году по 09.03.03 Системы КУ и при открытии его на редактирование дисциплин вылезает ошибка (http://orioks.miet.ru/prepare/bup/upd/?id=2463954&mode=bup)
![image](https://cloud.githubusercontent.com/assets/7606944/7179814/9c0d6818-e44c-11e4-995c-db8b1565697a.png)

**Comment by bereza-evgenij** [comment]
Вывод кафедры и названий ООП дисциплине не нашел (пункт 3)

**Comment by MsNatali** [comment]
2) Ошибка знаю почему - исправлю, но зачем создавать новый БУП в реальной БД, если можно делать что хочешь в тестовой с реальными БУПами?
3) На кнопку с глазом нажми

**Comment by MsNatali** [comment]
2) починила

**Comment by bereza-evgenij** [comment]
2) Я про тестовую БД забыл :)

**Comment by bereza-evgenij** [comment]
Для БУПов и ТУПов хорошо бы еще выводить выпускающую кафедру
