### ISSUE TITLE
Архивность объектов

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#311]
Это все тоже нужно срочно ЛПМ и кафедрам для подготовки к аккредитации.

При пометке ПБ, МП и ДОП на архивность нужно также архивными делать следующие связанные с ними объекты:
1. Дисциплины, которые не связанны ни с одним  активным ПБ, МП и ДОП.
2. БУПы и ТУПы этих ПБ, МП и ДОП. В этом случае думаю, что не нужно проверять на наличие групп у ТУПов, делать архивными в любом случае.

Соответственно ЛПМ в списке БУПов и ТУПов добавить фильтры на архивность: архивные, не архивные, все. По умолчанию не архивные.

**Comment by bereza-evgenij** [comment]
Ребят эту работу нужно срочно сделать!

**Comment by MadridianFox** [comment]
А если архивность снимается, то дочерние объекты тоже перестают быть архивными?

**Comment by MadridianFox** [comment]
А как быть с уже архивными ООП? Можно, конечно посидеть и вручную им галочки снять и поставить - их всего 24 штуки

**Comment by bereza-evgenij** [comment]
Да, архивность дочерних снимается

**Comment by bereza-evgenij** [comment]
ЛПМ вручную снимет и проставит галочки
