### ISSUE TITLE
Временное закрытие кафедрам доступа к загрузке ИР из раздела По ООП

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#314]
Из-за того, что обнаружились несоответствия ООП дисциплин ООП БУПов и ТУПов (т.е. в БУПе по ООП Системы корпоративного управления может быть дисциплина Математический анализ из ООП Применение математических методов...), временно (до середины лета я думаю) в пуле дисциплин в режиме По ООП кафедрам необходимо убрать возможность загрузки ИР и управления содержанием, т.е. останется просто список дисциплин с информацией по их ООП

**Comment by MsNatali** [comment]
Какой тогда кафедрам смысл от этого раздела? Посмотреть на соответствие Дисциплина - ООП, и то не факт что там нет ошибки?

**Comment by bereza-evgenij** [comment]
Посмотреть список дисциплин кафедры

**Comment by MsNatali** [comment]
Доступ к кнопкам оставила, но выбрать ООП в списке нельзя
http://orioks.miet.ru/prepare/pul/
![screenshot01211](https://cloud.githubusercontent.com/assets/8089373/7219213/0789c9ee-e69e-11e4-94fa-7820eda9cdef.png)
Или доступ к кнопкам тоже закрыть?

**Comment by bereza-evgenij** [comment]
Главное закрыть доступ к кнопкам. Я это и имел в виду изначально

С уважением, Берёза Евгений!

2015-04-19 14:12 GMT+03:00 MsNatali <notifications@github.com>:

**Comment by MsNatali** [comment]
Кнопки закрыла. А поиск по ооп оставить закрытым или открыть?

**Comment by bereza-evgenij** [comment]
Да оставь я думаю
