### ISSUE TITLE
А чем отличаются права с шифром dolg_schedule (Создание графика КМ для должников) и iup_schedule (Создание графика сдачи задолжностей)?

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#316]
Первое право для дисциплин должников, переводников и перепоступивших, а второе для дисциплин ФДДО что-ли?

**Comment by MadridianFox** [comment]
Ну есть ИУП_КМ а есть долги
соответственно есть такой и другой график
вот это два разрешения на редактирование двух графиков
вроде)

**Comment by bereza-evgenij** [comment]
Тогда лучше и назвать "Создание графика КМ для должников, переводников и перепоступивших" и "Создание графика КМ для дисциплин ИУПа". Если это так, а не опять дубли прав. 
Я на это наткнулся, чтобы исправить в отчете по графикам КМ для должников, переводников, перепоступивших, который сделал Владимиров Саша, ошибку прав доступа для ОКиО. С правом dolg_schedule все работает.

Хорошо бы в интерфейсе по работе с правами объектов добавить редактирование названий уже существующих прав и поиск прав по названию.

**Comment by MadridianFox** [comment]
Это к наташе =)

**Comment by bereza-evgenij** [comment]
Ну я знаю, что к Наташе :) Она у нас больше всех сделала и больше всех знает все кишки системы :)

**Comment by MsNatali** [comment]
Поиск прав. Ишь какой.Ладно, будет вам) Все равно я тесты ОРОКСа не хочу делать )
