### ISSUE TITLE
Дисциплины и компетенции

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#320]
Ребят,в БУП "2015 09.03.04 Программные технологии распределенной обработки информации" не удаляются дисциплины Физ-ра 4шт в 10 семестре, пишет что к ним прикреплены компетенции. В таблице link_komp_dis действительно есть записи о прикреплении к этим дисциплинам компетенций, но на сколько я помню сейчас компетенции крепятся к дисциплинам в рамках БУПа, т.к. нужно проверять наличие компетенций по таблице  link_komp_bup_d. 
Вань, тебе нужно рассказать Наташе об изменениях по структуре и набору таблиц, отвечающих за хранения компетенций, чтобы она исправила проверки в компонентах по работе с БУП и ТУП, либо в API внести изменения самому (если там есть что-то вроде метода удаления дисциплины БУПа/ТУПа).

**Comment by MadridianFox** [comment]
Да, есть такое - удаляя БУП+Д надо удалять link_bup_dis_komp

**Comment by bereza-evgenij** [comment]
В таблице link_bup_dis_komp не может быть записей для этих дисциплин.
Сейчас проверяется таблица link_dis_komp, а не должна

**Comment by MadridianFox** [comment]
есть link_komp_bup_d - старая таблица, я её только что отвязал
есть link_dis_komp - связывает дисциплину пула с компетенцией
есть link_bup_dis_komp - связывает link_dis_komp  с БУП+Д
При удалении БУП+Д внешний ключ может цепляться за link_bup_dis_komp  и мог цепляться за link_komp_bup_d
link_dis_komp тут никак не может мешать
