### ISSUE TITLE
Изменения по интерфейсу работы выпускающих кафедр с компетенциями

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#323]
1) В списке дисциплин БУПа, как мне кажется, не очень визуально понятно к какой именно дисциплине прикреплены компетенции: к той, которая сверху над лейблами с шифром, или к той, которая снизу. Предлагаю либо убрать разделитель между строкой с названием дисциплины и строкой со списком лейблов компетенций, либо разделитель между дисциплинами сделать жирнее. 
2) К плюсику возле названия дисциплины добавить всплывающею подсказку "Прикрепить компетенцию/подкомпетенцию".
3) Сортировать дисциплины БУПа, наверное, по семестру. В идеале иметь возможность сортировки по любому из столбцов (но это, наверное, сложно реализовать из-за строки с лейблами компетенций).
4) Группировать список компетенций по из типам (ОК, ПК, ОПК и ПКВ) и сортировать их внутри типа по номеру шифра.
5) У подкомпетенций временно убрать возможность создания подкомпетенций. Либо если наличие больше двух уровней декомпозиции компетенций не порушат отчеты по компетенциям (особенно отчет "Компетенции дисциплин в реализуемых УП"), то декомпозицию подкомпетенций можно оставить.

![image](https://cloud.githubusercontent.com/assets/7606944/7513158/10219efa-f4c3-11e4-9167-51cfbe879219.png)

**Comment by sokolovanat** [comment]
Я уже говорила, что хорошо бы сделать поиск сверху и компетенции и дисциплины. Особенно это удобно при связывании дисциплины с компетенцией

**Comment by bereza-evgenij** [comment]
Вот еще замечания от кафедр, которые передала Кирьянова Н.М.:
1. Неудобно делать скриншоты - схема не вмещается (это она про графическое представление компетенций. По-хорошему, нужно сохранение в картинку или файл, но я думаю это сложно делать)
2. Не сортирован список компетенций - трудно искать (это уже было выше)
3. Некоторые реализующие кафедры не видят подкомпетенции (пример ТМ)- они реально есть! (тут надо уточнять что именно они не видят. Я попробую узнать. Скорее всего опять проблема с тем, что не выбраны нужные виды деятельности)
4. Невозможно прикрепить несколько компетенций или подкомпетенций к одной дисциплине сразу - надо входить несколько раз и они перепрыгивают на другие места? (это видимо из-за того, что сохранение данных идет не через ajax, а через перезагрузку страницы)

**Comment by MadridianFox** [comment]
Пункты 2 и 4 уже закрытв
