### ISSUE TITLE
Просмотр неимпортированных баллов из журнала преподавателя

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#325]
До сих пор не все и далеко не все преподаватели знают о возможности импорта баллов у переводящихся с разных ТУПов студентов. Тем более чаще всего импортировать быллы не получается даже с помощью этого инструмента из-за кардинально расходящихся графиков. Я знаю, что есть возможности импорта баллов из одного КМ в несколько или из нескольких в одно, а также умножения балла на коэффициент, но даже я не до конца понимаю как их использовать, чтобы получить правильный результат. Преподаватели этого не понимают тем более.

Поэтому я предлагаю в журнал преподавателя для тех студентов, у которых есть "висящие" баллы, рядом с ФИО добавлять иконку, при нажатии на которую переходить в инструмент импорта баллов, передавая в него tpd дисциплины и id группы (а лучше numst студента, чтобы уменьшить список дисциплин, из которых можно импортировать баллы). А дальше преподаватели либо импортируют баллы, либо посмотрят их и сами проставят нужные баллы в журнал по графику КМ новой дисциплины.

И в инструмент импорта баллов к верхней таблице добавить подпись "В", а то лично я все время забываю, что это не "ИЗ". 
![image](https://cloud.githubusercontent.com/assets/7606944/7631859/9dc46fb8-fa58-11e4-9020-6733cedb589f.png)

**Comment by MsNatali** [comment]
Мне кажется плохой идеей делать в журнале поиск студентов с "висячими" баллами. Это только увеличение времени работы скрипта, а в большинстве ситуаций оно не надо.

Кнопку "импорт" сделать конечно можно, но одну для всего журнала. Правда по опыту хочу сказать, что из-за того, что мы кнопку "график КМ" продублировали в журнале, многие люди заходили в инструмент создания графика через журнал, не зная ВООБЩЕ о разделе "Подготовка". А в случае, когда график заполнялся на следующий семестр, журнал выдавал ошибку, что "дата начала семестра не определена" и ну ооочень много преподавателей негодовали по поводу того, как же добраться к графику. Так что с тех пор дублирование кнопок и ссылок разные интерфейсы не поддерживаю.

А по поводу того, что многие преподаватели до сих пор не знают про "импорт"- я давно предлагаю сделать инструмент, который позволит администрации портала доносить информацию о нововведения на сайте. Реализовать это довольно просто на самом деле.

Подпись "В", само собой сделаю.
