### ISSUE TITLE
Ошибка в отчете "Компетенции БУПа" 

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#326]
У кафедры МФЭ по БУПу 2012 210100.62 Микроэлектроника и твердотельная электроника не распределены только 3 компетенции/подкомпетенции из 80 (http://orioks.miet.ru/prepare/komp/?rp_id=1639751&rp_page=KompOfUp)
![image](https://cloud.githubusercontent.com/assets/7606944/7632538/23355e18-fa5f-11e4-8243-c1985c18b4b9.png)
А в отчете "Компетенции БУПа" (http://orioks.miet.ru/report/komp_first/?year=2012) в столбце "Декомпозиция компетенций (%)" указаны 55.56%, что явно не равно 3/80*100.
![image](https://cloud.githubusercontent.com/assets/7606944/7632751/e9ae2a10-fa60-11e4-96de-dc6d69510bab.png)

И было бы хорошо в интерфейсе выпускающей кафедры, если у компетенции есть подкомпетенции без дисциплин, то саму компетенцию тоже выделять красным

**Comment by bereza-evgenij** [comment]
И столбец "Декомпозиция компетенций (%)" из отчета "Компетенции БУПа" по-моему показывает то же самое, что и столбец "Компетенций обеспеченных дисцилпинами (%)" из отчета "Реализация компетенций"

**Comment by MadridianFox** [comment]
Декомпозиция компетенций показывает сколько компетенций из компетенций верхнего уровня разбито на подкомпетенции. Привязка компетенций/подкомпетенций никак не влияет на количество декомпозированных компетенций.
Компетенций обеспеченных дисцилпинами это как раз % компетенций верхнего уровня которые обеспечены дисцилпинами.
То что эти показатели не идентичны видно если посмотреть БУП того же МФЭ "2015 22.03.01 Технология материалов и наноструктур".

**Comment by bereza-evgenij** [comment]
А зачем тогда в отчете "Компетенции БУПа" вообще нужен столбец "Декомпозиция компетенций (%)"? Ведь не все компетенции должны быть декомпозированы

**Comment by bereza-evgenij** [comment]
И ты не закрывай тикет, там нужно подсветку доделать :)

**Comment by sokolovanat** [comment]
сейчас этот столбец может быть и не нужен, а в декабре с кафедр требовали, чтобы все компетенции были декомпозированы

**Comment by bereza-evgenij** [comment]
А вообще правда, ведь в итоге все компетенции должны быть декомпозированы, просто какие-то из них будут связаны с элементами дисциплины. Тогда столбец нужный
