### ISSUE TITLE
Добавить возможность смена вида деятельности у компетенции вуза

### ISSUE THREAD

**Issue by bereza-evgenij** [rpk-miet-ru/RP#327]
![image](https://cloud.githubusercontent.com/assets/7606944/7744913/3a211a0a-ffb8-11e4-8942-47827a5f2d9c.png)

**Comment by MadridianFox** [comment]
![1370197512435](https://cloud.githubusercontent.com/assets/3392587/7744984/70feef78-ffb0-11e4-9a48-443129d0e7b6.jpg)

**Comment by bereza-evgenij** [comment]
:)
