### ISSUE TITLE
Реализация обучения по дополнительным программам

### ISSUE THREAD

**Issue by sokolovanat** [rpk-miet-ru/RP#329]
Мы можем в системе делать БУП для ДОП, но не можем работать с группами. У нас есть один слушатель, заведенный в 1С, но там мы не можем назначить группу (это другой вопрос, мы его постараемся решить). Еще проблема. Сейчас нет доступа к содержимому дисциплины , если даже дисциплина включена в текущий учебный план, но при подготовке содержания не всегда есть уже группы. Сейчас это связанно с каф. Иняз. Когда будет открыт доступ к пулу и есть ли какая-то возможность сейчас наполнять дисциплину пула, если есть текущий учебный план 2015 года, но группы не назначены.

**Comment by MsNatali** [comment]
Закрытие доступа было связано с тем, что ООП БУПа и ООП дисциплины из БУПа не совпадали у каких-то дисциплин. сделать закрытие доступа к содержимому через ПУЛ в режиме по ООП просил Женя. Может надо у ЛПМ спросить, можно ли уже открыть?
